### ISSUE TITLE
참고한 코드의 라이센스가 이행되지 않았습니다.

### ISSUE THREAD

**Issue by juna1221** [withadoctor/discord.js-v12-bot#1]
참고하신 코드 (Miya) 레포는 GNUv3 라이센스로 코드 사용 시 라이센스를 똑같이 GNUv3 를 써야할 의무를 지니고 있습니다.    
Miya 레포도 라이센스가 GNUv3인 다른 코드를 참고하였기에 GNUv3 라이센스를 사용한 것 입니다.

**Comment by withadoctor** [comment]
https://github.com/wonderlandpark/wonderbot/
님의 어느 부분을 사용하셨습니까?

**Comment by withadoctor** [comment]
주석
https://github.com/wonderlandpark/wonderbot/blob/master/src/commands/dev/eval.js
이라고 말씀하셨습니다.
